services:
  # Twilio Voice Agent (with built-in reverse proxy)
  # Runs both UI (port 3000) and Twilio server (port 5050) internally
  # Exposes single port with routing: /twilio/* -> 5050, /* -> 3000
  - type: web
    name: twilio-voice-agent
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: PUBLIC_DOMAIN
        sync: false
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /twilio/health

# Architecture Note:
# This deployment uses a built-in reverse proxy (server/proxy.ts) that:
# 1. Listens on the PORT environment variable (set by Render)
# 2. Starts both the UI server (port 3000) and Twilio server (port 5050) internally
# 3. Routes requests: /twilio/* → port 5050, everything else → port 3000
#
# After deployment:
# 1. Set environment variables in Render dashboard
# 2. Update PUBLIC_DOMAIN to your Render URL (e.g., https://your-app.onrender.com)
# 3. Test the deployment by visiting your URL
