services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - ..:/workspaces/twilio-voice-agent:cached
      - ~/.gitconfig:/home/node/.gitconfig:cached
    command: sleep infinity
    env_file:
      - ../.env
    networks:
      - devnet

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    env_file:
      - .cloudflared.env
    command: ["tunnel", "--no-autoupdate", "run", "--protocol", "http2"]
    depends_on:
      - app
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
